"""Add enhanced destination fields

Revision ID: bc3ee4b578e7
Revises: 513d50d5d008
Create Date: 2025-10-29 21:57:22.278953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc3ee4b578e7'
down_revision = '513d50d5d008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guide_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('duration_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('included_amenities', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('itinerary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('max_travelers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('images', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_destinations_guide_id', 'guides', ['guide_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('images')
        batch_op.drop_column('max_travelers')
        batch_op.drop_column('itinerary')
        batch_op.drop_column('included_amenities')
        batch_op.drop_column('duration_days')
        batch_op.drop_column('guide_id')

    # ### end Alembic commands ###
